# Generated by Django 4.1.7 on 2023-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/chat_images/'),
        ),
    ]
