# Generated by Django 4.1.7 on 2023-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessages_can_forward_alter_chatmessages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
